import { Schema, model, Document } from 'mongoose';
import { IOperation } from '../types';

/**
 * Operation Model — The core event log. Append-only.
 *
 * Design decisions:
 * - APPEND-ONLY: Operations are NEVER updated or deleted after insert.
 *   This is fundamental to CRDT/event-sourcing correctness and auditability.
 *
 * - `version` is strictly monotonically increasing per document.
 *   Assigned by the server (not the client) to prevent ordering conflicts.
 *   Compound unique index (docId, version) enforces this at the DB level.
 *
 * - `clientId` is a UUID generated by the client to deduplicate
 *   re-submitted operations (e.g., after a reconnect). If we see a
 *   clientId we've already processed, we return the cached result.
 *
 * - `op` stores the CRDT delta as flexible JSON.
 *   The CRDT service handles merge logic; this model is storage-only.
 *
 * Reconstruction algorithm:
 *   1. Find latest Version snapshot for docId
 *   2. Fetch all Operations where version > snapshot.versionNumber
 *   3. Apply ops in order to reconstruct current document state
 *
 * Scalability:
 * - (docId, version) is the primary query pattern for reconstruction
 * - Compound index ensures O(log n) range scans, not full collection scans
 * - TTL index could be added to archive very old ops (e.g., > 1 year)
 */

export type OperationDocument = IOperation & Document;

const CRDTOpSchema = new Schema(
  {
    type: {
      type: String,
      enum: ['insert', 'delete', 'retain', 'replace'],
      required: true,
    },
    pos: { type: Number, required: true },
    text: { type: String },       // for insert / replace
    length: { type: Number },     // for delete / retain
    attrs: { type: Schema.Types.Mixed }, // rich-text attributes
  },
  { _id: false }
);

const OperationSchema = new Schema<OperationDocument>(
  {
    docId: {
      type: Schema.Types.ObjectId,
      ref: 'Document',
      required: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    op: {
      type: CRDTOpSchema,
      required: true,
    },
    // Server-assigned version number (NOT client version)
    version: {
      type: Number,
      required: true,
      min: 1,
    },
    // Client-generated UUID for idempotent operation submission
    clientId: {
      type: String,
      sparse: true, // allow null but index non-null values
    },
    timestamp: {
      type: Date,
      default: () => new Date(),
    },
  },
  {
    versionKey: false,
    // No timestamps: we have explicit `timestamp` field
    // No updates allowed — collection is append-only
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

// PRIMARY: Compound unique — enforces strict ordering per document
// Used for reconstruction: "give me ops for docId where version > N"
OperationSchema.index({ docId: 1, version: 1 }, { unique: true });

// Deduplication lookup: "has this clientId been processed for this doc?"
OperationSchema.index({ docId: 1, clientId: 1 }, { sparse: true });

// Audit: "show all ops by a user across all documents"
OperationSchema.index({ userId: 1, timestamp: -1 });

// Future: TTL-based archival — uncomment to auto-delete ops older than 1 year
// OperationSchema.index({ timestamp: 1 }, { expireAfterSeconds: 365 * 24 * 3600 });

export const Operation = model<OperationDocument>('Operation', OperationSchema);
